"""Alle ORM-Modelle importieren, damit Alembic sie in Base.metadata findet."""

from app.models.coordination_time import CoordinationTimeRecord
from app.models.family import Family, FamilyMember, FamilyMemberType, FamilyStatus
from app.models.identity import (
    AuditEvent,
    Invitation,
    PasswordResetToken,
    PlatformRole,
    RefreshToken,
    StaffMembership,
    StaffRole,
    User,
    UserStatus,
)
from app.models.organization import (
    CrewSizeRule,
    HomeVenue,
    MenuType,
    Organization,
    OrganizationSettings,
    Theme,
)
from app.models.planning import (
    ClubYear,
    Event,
    EventStatus,
    GrillShiftDecision,
    ImportBatch,
    ImportBatchStatus,
    ImportRow,
    ImportRowClassification,
    ImportRowDecision,
    PlanningStatus,
    Season,
    SeasonType,
    Shift,
    ShiftAssignmentMode,
    ShiftStatus,
    ShiftType,
    Signup,
    SignupOutcome,
    SignupSource,
    SignupStatus,
    SpielTyp,
    Volunteer,
    VolunteerStatus,
)
from app.models.work_record import CompensationType, PayoutStatus, WorkRecord

__all__ = [
    "AuditEvent",
    "ClubYear",
    "CompensationType",
    "CoordinationTimeRecord",
    "CrewSizeRule",
    "Event",
    "EventStatus",
    "Family",
    "FamilyMember",
    "FamilyMemberType",
    "FamilyStatus",
    "GrillShiftDecision",
    "HomeVenue",
    "ImportBatch",
    "ImportBatchStatus",
    "ImportRow",
    "ImportRowClassification",
    "ImportRowDecision",
    "Invitation",
    "MenuType",
    "Organization",
    "OrganizationSettings",
    "PasswordResetToken",
    "PayoutStatus",
    "PlanningStatus",
    "PlatformRole",
    "RefreshToken",
    "Season",
    "SeasonType",
    "Shift",
    "ShiftAssignmentMode",
    "ShiftStatus",
    "ShiftType",
    "Signup",
    "SignupOutcome",
    "SignupSource",
    "SignupStatus",
    "SpielTyp",
    "StaffMembership",
    "StaffRole",
    "Theme",
    "User",
    "UserStatus",
    "Volunteer",
    "VolunteerStatus",
    "WorkRecord",
]
